
import javax.swing.JFrame;

/*
 *  Klasa MenuKlient
 *
 *  Klasa pozwala na stworzenie konta klienta, zalogowanie sie 
 *  oraz powrot do glownego menu.
 *
 *  Autor: Adam Filipowicz
 *  Data: 31 maja 2017 r.
 */
public class MenuKlient extends MenuGlowne {
    protected static StworzKonto stworzKonto;
    protected static Opcje opcje;
    private Konto konto;
    
    public MenuKlient() {
        super(5);
        initComponents();
    }
    
    public MenuKlient(int i){
        super(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        stworzKontoButton = new javax.swing.JButton();
        zalogujSieButton = new javax.swing.JButton();
        wrocButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Menu klienta");

        stworzKontoButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        stworzKontoButton.setText("Stworz konto");
        stworzKontoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stworzKontoButtonActionPerformed(evt);
            }
        });

        zalogujSieButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        zalogujSieButton.setText("Zaloguj sie");
        zalogujSieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujSieButtonActionPerformed(evt);
            }
        });

        wrocButton.setText("Wroc do menu glownego");
        wrocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(wrocButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(stworzKontoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(zalogujSieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stworzKontoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zalogujSieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(wrocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda po nacisnieciu guzika przechodzi do tworzenia konta klienta.
     * @param evt - nacisniecie guzika powoduje przejscie do tworzenia konta klienta
     */
    private void stworzKontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stworzKontoButtonActionPerformed
        stworzKonto = new StworzKonto();
        stworzKonto.setResizable(false);
        stworzKonto.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        stworzKonto.setSize(800,500);
        stworzKonto.setLocation(500,250);
        stworzKonto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_stworzKontoButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na zalogowanie sie i przejscia do opcji konta.
     * @param evt - nacisniecie guzika powoduje mozliwosc zalogowania sie
     */
    private void zalogujSieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujSieButtonActionPerformed
        String nazwa;

        String haslo;

        UI.printMessage("\nLOGOWANIE DO KONTA\n");
        nazwa = UI.enterString("Podaj nazwe konta:");
        haslo = UI.enterString("Podaj haslo:");
        konto = wypozyczalnia.znajdzKonto(nazwa,haslo);
        if (konto == null) {
            UI.printErrorMessage("Bledne dane");
            return;
        }
        if(wypozyczalnia.sprawdzCzyKontoSprzedawcy(konto)){
            UI.printErrorMessage("Probujesz zalogowac sie na konto sprzedawcy");
            return;
        }
        opcje = new Opcje(konto);
        opcje.setResizable(false);
        opcje.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        opcje.setSize(800,500);
        opcje.setLocation(500,250);
        opcje.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_zalogujSieButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika wraca do glownego menu.
     * @param evt - nacisniecie guzika powoduje powrot do glownego menu
     */
    private void wrocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocButtonActionPerformed
        glowneMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_wrocButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuKlient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuKlient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton stworzKontoButton;
    private javax.swing.JButton wrocButton;
    private javax.swing.JButton zalogujSieButton;
    // End of variables declaration//GEN-END:variables
}
