
import javax.swing.JFrame;

/*
 *  Klasa MenuSprzedawca
 *
 *  Klasa pozwala na stworzenie konta sprzedawcy, zalogowanie sie 
 *  oraz powrot do glownego menu.
 *
 *  Autor: Adam Filipowicz
 *  Data: 31 maja 2017 r.
 */
public class MenuSprzedawca extends MenuGlowne {
    public static OpcjeS opcje;
    private Konto konto;
    
    public MenuSprzedawca() {
        super(5);
        initComponents();
    }
    
    public MenuSprzedawca(int i){
        super(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zalogujSieSButton = new javax.swing.JButton();
        stworzKontoSButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        wrocSButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        zalogujSieSButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        zalogujSieSButton.setText("Zaloguj sie");
        zalogujSieSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujSieSButtonActionPerformed(evt);
            }
        });

        stworzKontoSButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        stworzKontoSButton.setText("Stworz konto");
        stworzKontoSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stworzKontoSButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Menu sprzedawcy");

        wrocSButton.setText("Wroc do menu glownego");
        wrocSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocSButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(wrocSButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(stworzKontoSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(zalogujSieSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zalogujSieSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stworzKontoSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(wrocSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda po nacisnieciu guzika pozwala stworzyc konto sprzedawcy.
     * @param evt - nacisniecie guzika powoduje tworzenie konta sprzedawcy
     */
    private void stworzKontoSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stworzKontoSButtonActionPerformed
        String nazwa; //Nazwa nowego konta.

        String haslo; //Haslo nowego konta.
        
        UI.printMessage("\nTWORZENIE NOWEGO KONTA\n");
        while(true) {
            if(wypozyczalnia.sprawdzCzyIstniejeSprzedawca()){
                UI.printErrorMessage("Konto sprzedawcy zostalo juz stworzone");
                return;
            }
            nazwa = UI.enterString("Wybierz nazwe konta:");
            if (nazwa.equals("")){
                UI.printErrorMessage("Nie podano nazwy konta");
                return;
            }
            if (wypozyczalnia.znajdzKonto(nazwa)!=null) {
                UI.printErrorMessage("Konto juz istnieje");
                continue;
            }
            haslo = UI.enterString("Podaj haslo:");
            try {
                konto = wypozyczalnia.zalozKontoSprzedawcy(nazwa);
                konto.setHaslo("", haslo);
            }
            catch (Exception e) {
                UI.printErrorMessage(e.getMessage());
                continue;
            }
            UI.printInfoMessage("Konto zostalo utworzone");
            break;
        }
    }//GEN-LAST:event_stworzKontoSButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na zalogowanie sie i przejscia do opcji konta.
     * @param evt - nacisniecie guzika powoduje mozliwosc zalogowania sie
     */
    private void zalogujSieSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujSieSButtonActionPerformed
        
        String nazwa; //Nazwa nowego konta.

        String haslo; //Haslo nowego konta.

        UI.printMessage("\nLOGOWANIE DO KONTA-SPRZEDAWCA\n");
        nazwa = UI.enterString("Podaj nazwe konta:");
        haslo = UI.enterString("Podaj haslo:");
        konto = wypozyczalnia.znajdzKonto(nazwa,haslo);
        if (konto == null) {
            UI.printErrorMessage("Bledne dane");
            return;
        }
        if(!wypozyczalnia.sprawdzCzyKontoSprzedawcy(konto)){
            UI.printErrorMessage("Probujesz zalogowac sie na inne konto niz sprzedawcy");
            return;
        }
        
        opcje = new OpcjeS(konto);
        opcje.setResizable(false);
        opcje.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        opcje.setSize(800,500);
        opcje.setLocation(500,250);
        opcje.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_zalogujSieSButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika wraca do glownego menu.
     * @param evt - nacisniecie guzika powoduje powrot do glownego menu
     */
    private void wrocSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocSButtonActionPerformed
        glowneMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_wrocSButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSprzedawca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSprzedawca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSprzedawca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSprzedawca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuSprzedawca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton stworzKontoSButton;
    private javax.swing.JButton wrocSButton;
    private javax.swing.JButton zalogujSieSButton;
    // End of variables declaration//GEN-END:variables
}
