
import javax.swing.JFrame;

/*
 *  Klasa WypozyczFilm
 *
 *  Klasa wyswietla wybrany wczesniej film i jego nazwe, cene, ilosc oraz opis.
 *  Klasa pozwala na wpisanie interesujacej nas ilosci filmu i przejscie do platnosci.
 *  Powala takze na powrot do opcji klienta.
 *
 *  Autor: Adam Filipowicz
 *  Data: 31 maja 2017 r.
 */
public class WypozyczFilm extends Opcje {
    public static Platnosc platnosc;
    private int liczbaSztuk;
    private Konto konto;
    private Film film;

    public WypozyczFilm(){
        super(5);
        initComponents();
    }
  
    public WypozyczFilm(Konto konto, Film film){
        super(5);
        initComponents();
        this.konto=konto;
        this.film=film;
        nazwaText.setText("Nazwa filmu: "+film.getNazwa());
        cenaText.setText("Cena wypozyczenia: "+film.getCena());
        iloscText.setText("Pozostala ilosc: "+film.getIlosc());
        opisText.setText("Opis: "+film.getOpis());
    }
    
    public WypozyczFilm(int i){
        super(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nazwaText = new javax.swing.JTextField();
        cenaText = new javax.swing.JTextField();
        iloscText = new javax.swing.JTextField();
        opisText = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        wrocButton = new javax.swing.JButton();
        platnoscButton = new javax.swing.JButton();
        iloscWypozyczanychText = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nazwaText.setEditable(false);
        nazwaText.setText("Nazwa filmu: ");

        cenaText.setEditable(false);
        cenaText.setText("Cena: ");

        iloscText.setEditable(false);
        iloscText.setText("Pozostala ilosc: ");

        opisText.setEditable(false);
        opisText.setText("Opis: ");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Wypozycz film");

        wrocButton.setText("Wroc do konta");
        wrocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocButtonActionPerformed(evt);
            }
        });

        platnoscButton.setText("Przejdz do platnosci");
        platnoscButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platnoscButtonActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setText("Ilosc wypozyczanych filmow");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(wrocButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opisText)
                            .addComponent(iloscText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cenaText)
                            .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(iloscWypozyczanychText, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(platnoscButton)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iloscText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iloscWypozyczanychText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(platnoscButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(wrocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda po nacisnieciu guzika wraca do opcji klienta.
     * @param evt - nacisniecie guzika powoduje powrot do opcji klienta
     */
    private void wrocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocButtonActionPerformed
        opcje.setVisible(true);
        opcje.aktualizujFilmyIDostepnosc();
        this.setVisible(false);
    }//GEN-LAST:event_wrocButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika przechodzi do platnosci o ile wpisano odpowiednia ilosc filmu.
     * @param evt - nacisniecie guzika powoduje przejscie do platnosci
     */
    private void platnoscButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platnoscButtonActionPerformed
        liczbaSztuk=Integer.parseInt(iloscWypozyczanychText.getText()); //Liczba sztuk filmu ktora chcemy wypozyczyc.

        if(liczbaSztuk==0) {
            UI.printErrorMessage("\nPodano 0 sztuk filmu");
            return;
        }
        if(liczbaSztuk>film.getIlosc()){
            UI.printErrorMessage("W wypozyczalni nie ma wystarczajacej ilosci filmu");
            return;
        }
        if(liczbaSztuk<0) {
            UI.printErrorMessage("\nIlosc filmow mniejsza niz 0");
            return;
        }
        platnosc = new Platnosc(konto,film,liczbaSztuk);
        platnosc.setResizable(false);
        platnosc.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        platnosc.setSize(800,500);
        platnosc.setLocation(500,250);
        platnosc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_platnoscButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WypozyczFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WypozyczFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cenaText;
    private javax.swing.JTextField iloscText;
    private javax.swing.JTextField iloscWypozyczanychText;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField nazwaText;
    private javax.swing.JTextField opisText;
    private javax.swing.JButton platnoscButton;
    private javax.swing.JButton wrocButton;
    // End of variables declaration//GEN-END:variables
}
